"""add allow_prepayment to debts

Revision ID: 2960f7c8dcc5
Revises: b3e7d9f01c22
Create Date: 2026-05-02 22:52:49.018756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2960f7c8dcc5'
down_revision: Union[str, Sequence[str], None] = 'b3e7d9f01c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('allow_prepayment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'allow_prepayment')
    # ### end Alembic commands ###
