"""add_email_verification_to_users

Revision ID: 356a54fd4cf9
Revises: 6cabba381573
Create Date: 2026-05-06 12:32:35.755008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356a54fd4cf9'
down_revision: Union[str, Sequence[str], None] = '6cabba381573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
    op.add_column('users', sa.Column('verify_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('verify_token_expiry', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'verify_token_expiry')
    op.drop_column('users', 'verify_token')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
